### PR TITLE
Added VehicleHealth

### PR DESCRIPTION
**Pull request by stboch**
Added VehicleHealth, still need to add tests functions.

### CODE REVIEW

**Review by G-Two — APPROVED** [review]
This is great, thanks!

**Comment by stboch** [comment]
Sorry didn't get to updating the tests, the  Flu been keeping me busy all week.

**Comment by G-Two** [comment]
No problem, I'll add them now. They're horribly written and barely maintainable, so it's probably fastest if I do them real quick. Do you happen to know the format of the dates that the subaru API provides for the MILs (e.g. string, timestamp)?

**Comment by stboch** [comment]
I'll get you an example but I believe it was a list of unixtimestamps in milliseconds.

**Comment by stboch** [comment]
`'data': {'lastUpdatedDate': 1670793543000,
                     'vehicleHealthItems': [{'b2cCode': 'blindspot',
                                             'featureCode': 'BSDRCT_MIL',
                                             'isTrouble': False,
                                             'onDaiId': 0,
                                             'onDates': [],
                                             'warningCode': 39},
                                            {'b2cCode': 'vdc',
                                             'featureCode': 'VDC_MIL',
                                             'isTrouble': False,
                                             'onDaiId': 0,
                                             'onDates': [],
                                             'warningCode': 7},
                                            {'b2cCode': 'oilPres',
                                             'featureCode': 'OPL_MIL',
                                             'isTrouble': False,
                                             'onDaiId': 0,
                                             'onDates': [],
                                             'warningCode': 53},
                                            {'b2cCode': 'awd',
                                             'featureCode': 'AWD_MIL',
                                             'isTrouble': False,
                                             'onDaiId': 0,
                                             'onDates': [],
                                             'warningCode': 5},
                                            {'b2cCode': 'oilWarning',
                                             'featureCode': 'EOL_MIL',
                                             'isTrouble': False,
                                             'onDaiId': 0,
                                             'onDates': [],
                                             'warningCode': 3},
                                            {'b2cCode': 'eyesight',
                                             'featureCode': 'ESS_MIL',
                                             'isTrouble': False,
                                             'onDaiId': 0,
                                             'onDates': [],
                                             'warningCode': 12},
                                            {'b2cCode': 'telematics',
                                             'featureCode': 'TEL_MIL',
                                             'isTrouble': False,
                                             'onDaiId': 0,
                                             'onDates': [],
                                             'warningCode': 14},
                                            {'b2cCode': 'iss',
                                             'featureCode': 'ISS_MIL',
                                             'isTrouble': False,
                                             'onDaiId': 0,
                                             'onDates': [],
                                             'warningCode': 50},
                                            {'b2cCode': 'abs',
                                             'featureCode': 'ABS_MIL',
                                             'isTrouble': False,
                                             'onDaiId': 0,
                                             'onDates': [],
                                             'warningCode': 6},
                                            {'b2cCode': 'revBrake',
                                             'featureCode': 'RAB_MIL',
                                             'isTrouble': False,
                                             'onDaiId': 0,
                                             'onDates': [],
                                             'warningCode': 69},
                                            {'b2cCode': 'tpms',
                                             'featureCode': 'TPMS_MIL',
                                             'isTrouble': False,
                                             'onDaiId': 0,
                                             'onDates': [],
                                             'warningCode': 9},
                                            {'b2cCode': 'washer',
                                             'featureCode': 'WASH_MIL',
                                             'isTrouble': True,
                                             'onDaiId': 421622375,
                                             'onDates': [1666632135000],
                                             'warningCode': 1},
                                            {'b2cCode': 'epas',
                                             'featureCode': 'EPAS_MIL',
                                             'isTrouble': False,
                                             'onDaiId': 0,
                                             'onDates': [],
                                             'warningCode': 11},
                                            {'b2cCode': 'pkgBrake',
                                             'featureCode': 'EPB_MIL',
                                             'isTrouble': False,
                                             'onDaiId': 0,
                                             'onDates': [],
                                             'warningCode': 44},
                                            {'b2cCode': 'ebd',
                                             'featureCode': 'EBD_MIL',
                                             'isTrouble': False,
                                             'onDaiId': 0,
                                             'onDates': [],
                                             'warningCode': 8},
                                            {'b2cCode': 'oilTemp',
                                             'featureCode': 'ATF_MIL',
                                             'isTrouble': False,
                                             'onDaiId': 0,
                                             'onDates': [],
                                             'warningCode': 4},
                                            {'b2cCode': 'engineFail',
                                             'featureCode': 'CEL_MIL',
                                             'isTrouble': False,
                                             'onDaiId': 0,
                                             'onDates': [],
                                             'warningCode': 2},
                                            {'b2cCode': 'airbag',
                                             'featureCode': 'SRS_MIL',
                                             'isTrouble': False,
                                             'onDaiId': 0,
                                             'onDates': [],
                                             'warningCode': 10},
                                            {'b2cCode': 'ahbl',
                                             'featureCode': 'AHBL_MIL',
                                             'isTrouble': False,
                                             'onDaiId': 0,
                                             'onDates': [],
                                             'warningCode': 30}]}`

**Pull request merged**
